#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Tue Jul  7 10:45:44 2020
#

import wx


# begin wxGlade: dependencies
# end wxGlade

class MyNumberValidator(wx.Validator):
    def __init__(self):
        wx.Validator.__init__(self)
        self.ValidInput = ['.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
        self.StringLength = 0
        self.Bind(wx.EVT_CHAR, self.OnCharChanged)  # 绑定字符改变事件

    def OnCharChanged(self, event):
        # 得到输入字符的ASCⅡ码
        keycode = event.GetKeyCode()
        # 退格键（ASCⅡ码 为 8），删除一个字符
        if keycode == 8:
            self.StringLength -= 1
            # 时间继续传递
            event.Skip()
            return

        # 把ASCⅡ码转换为字符
        input_char = chr(keycode)

        if input_char in self.ValidInput:
            # 第一个字符为“.” 非法，拦截该事件，不会成功输入
            if input_char == '.' and self.StringLength == 0:
                return False
            else:
                event.Skip()
                self.StringLength += 1
                return True
        return False

    def Clone(self):
        return MyNumberValidator()

    def Validate(self, win):  # 1 使用验证器方法
        return True

    def TransferToWindow(self):
        return True

    def TransferFromWindow(self):
        return True


# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style",
                                 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1600, 900))

        self.data = {}

        self.main_frame_statusbar = self.CreateStatusBar(1)
        self.new_data_button = wx.Button(self, wx.ID_ANY, u"新建")
        self.open_data_button = wx.Button(self, wx.ID_ANY, u"打开")
        self.save_data_button = wx.Button(self, wx.ID_ANY, u"保存")
        self.export_data_button = wx.Button(self, wx.ID_ANY, u"导出")
        self.show_help_button = wx.Button(self, wx.ID_ANY, u"帮助")
        self.show_info_button = wx.Button(self, wx.ID_ANY, u"关于")
        self.add_contract_button = wx.Button(self, wx.ID_ANY, u"➕")
        self.remove_contract_button = wx.Button(self, wx.ID_ANY, u"➖")
        self.contract_moveup_button = wx.Button(self, wx.ID_ANY, u"↑")
        self.contract_movedown_button = wx.Button(self, wx.ID_ANY, u"↓")
        self.contract_list_ctrl = wx.ListCtrl(self, wx.ID_ANY,
                                              style=wx.BORDER_DEFAULT | wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_VRULES)
        self.work_title_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, u"数据文件标题", style=wx.TE_CENTRE)
        self.contract_ID_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "")
        self.contract_title_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "")
        self.contract_supplier_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "")
        self.contract_signed_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                          choices=["2015", "2016", "2017", "2018", "2019", "2020",
                                                                   "2021", "2022", "2023", "2024", "2025"],
                                                          style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.contract_signed_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                           choices=["01", "02", "03", "04", "05", "06", "07", "08",
                                                                    "09", "10", "11", "12"],
                                                           style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.contract_total_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "0", style=wx.TE_CENTRE)
        self.pay_no1_checkbox = wx.CheckBox(self, wx.ID_ANY, "1         ", style=wx.ALIGN_RIGHT)
        self.pay_no1_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no1_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no1_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no1_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no1_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.pay_no2_checkbox = wx.CheckBox(self, wx.ID_ANY, "2         ", style=wx.ALIGN_RIGHT)
        self.pay_no2_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no2_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no2_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no2_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no2_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.pay_no3_checkbox = wx.CheckBox(self, wx.ID_ANY, "3         ", style=wx.ALIGN_RIGHT)
        self.pay_no3_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no3_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no3_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no3_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no3_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.pay_no4_checkbox = wx.CheckBox(self, wx.ID_ANY, "4         ", style=wx.ALIGN_RIGHT)
        self.pay_no4_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no4_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no4_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no4_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no4_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.pay_no5_checkbox = wx.CheckBox(self, wx.ID_ANY, "5         ", style=wx.ALIGN_RIGHT)
        self.pay_no5_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no5_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no5_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no5_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no5_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.pay_no6_checkbox = wx.CheckBox(self, wx.ID_ANY, "6         ", style=wx.ALIGN_RIGHT)
        self.pay_no6_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no6_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no6_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no6_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no6_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.pay_no7_checkbox = wx.CheckBox(self, wx.ID_ANY, "7         ", style=wx.ALIGN_RIGHT)
        self.pay_no7_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no7_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no7_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no7_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no7_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.pay_no8_checkbox = wx.CheckBox(self, wx.ID_ANY, "8         ", style=wx.ALIGN_RIGHT)
        self.pay_no8_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no8_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no8_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no8_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no8_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.pay_no9_checkbox = wx.CheckBox(self, wx.ID_ANY, "9         ", style=wx.ALIGN_RIGHT)
        self.pay_no9_info_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.pay_no9_year_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                  choices=["2015", "2016", "2017", "2018", "2019", "2020", "2021",
                                                           "2022", "2023", "2024", "2025"],
                                                  style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no9_mouth_combo_box = wx.ComboBox(self, wx.ID_ANY,
                                                   choices=["01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                                                            "11", "12"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.pay_no9_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_CENTRE)
        self.is_paid_no9_checkbox = wx.CheckBox(self, wx.ID_ANY, "")
        self.contract_paid_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "0", style=wx.TE_CENTRE | wx.TE_READONLY)
        self.contract_rest_money_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "0", style=wx.TE_CENTRE | wx.TE_READONLY)
        self.contract_paid_proportion_text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "0%",
                                                              style=wx.TE_CENTRE | wx.TE_READONLY)
        self.save_contract_button = wx.Button(self, wx.ID_ANY, u"保 存 当 前 合 同 信 息")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.new_data, self.new_data_button)
        self.Bind(wx.EVT_BUTTON, self.open_data, self.open_data_button)
        self.Bind(wx.EVT_BUTTON, self.save_data, self.save_data_button)
        self.Bind(wx.EVT_BUTTON, self.export_data, self.export_data_button)
        self.Bind(wx.EVT_BUTTON, self.show_help, self.show_help_button)
        self.Bind(wx.EVT_BUTTON, self.show_info, self.show_info_button)
        self.Bind(wx.EVT_BUTTON, self.add_contract, self.add_contract_button)
        self.Bind(wx.EVT_BUTTON, self.remove_contract, self.remove_contract_button)
        self.Bind(wx.EVT_BUTTON, self.contract_moveup, self.contract_moveup_button)
        self.Bind(wx.EVT_BUTTON, self.contract_movedown, self.contract_movedown_button)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.load_contract, self.contract_list_ctrl)
        self.Bind(wx.EVT_TEXT, self.work_title_change, self.work_title_text_ctrl)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.contract_total_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no1_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no1_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no1_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no2_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no2_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no2_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no3_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no3_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no3_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no4_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no4_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no4_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no5_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no5_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no5_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no6_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no6_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no6_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no7_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no7_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no7_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no8_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no8_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no8_checkbox)
        self.Bind(wx.EVT_CHECKBOX, self.pay_enable, self.pay_no9_checkbox)
        self.Bind(wx.EVT_TEXT, self.pay_money_changed, self.pay_no9_money_text_ctrl)
        self.Bind(wx.EVT_CHECKBOX, self.pay_money_changed, self.is_paid_no9_checkbox)
        self.Bind(wx.EVT_BUTTON, self.save_contract, self.save_contract_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(u"合同金额统计")
        self.main_frame_statusbar.SetStatusWidths([-1])

        # statusbar fields
        main_frame_statusbar_fields = ["main_frame_statusbar"]
        for i in range(len(main_frame_statusbar_fields)):
            self.main_frame_statusbar.SetStatusText(main_frame_statusbar_fields[i], i)
        self.new_data_button.SetMinSize((75, 25))
        self.open_data_button.SetMinSize((75, 25))
        self.save_data_button.SetMinSize((75, 25))
        self.export_data_button.SetMinSize((75, 25))
        self.show_help_button.SetMinSize((75, 25))
        self.show_info_button.SetMinSize((75, 25))
        self.add_contract_button.SetMinSize((25, 25))
        self.remove_contract_button.SetMinSize((25, 25))
        self.contract_moveup_button.SetMinSize((25, 25))
        self.contract_movedown_button.SetMinSize((25, 25))
        self.contract_list_ctrl.AppendColumn(u"合同编号", format=wx.LIST_FORMAT_LEFT, width=77)
        self.contract_list_ctrl.AppendColumn(u"名称", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.contract_list_ctrl.AppendColumn(u"供应商", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.contract_list_ctrl.AppendColumn(u"签订时间", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.work_title_text_ctrl.SetMinSize((600, 35))
        self.work_title_text_ctrl.SetFont(
            wx.Font(17, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_ID_text_ctrl.SetMinSize((200, 35))
        self.contract_ID_text_ctrl.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_title_text_ctrl.SetMinSize((500, 35))
        self.contract_title_text_ctrl.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_supplier_text_ctrl.SetMinSize((200, 35))
        self.contract_supplier_text_ctrl.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_signed_year_combo_box.SetMinSize((69, 31))
        self.contract_signed_year_combo_box.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_signed_year_combo_box.SetSelection(5)
        self.contract_signed_mouth_combo_box.SetMinSize((49, 31))
        self.contract_signed_mouth_combo_box.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_total_money_text_ctrl.SetMinSize((150, 35))
        self.contract_total_money_text_ctrl.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_total_money_text_ctrl.SetValidator(MyNumberValidator())
        self.pay_no1_checkbox.SetMinSize((90, 25))
        self.pay_no1_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no1_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no1_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no1_info_text_ctrl.Enable(False)
        self.pay_no1_year_combo_box.SetMinSize((60, 25))
        self.pay_no1_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no1_year_combo_box.Enable(False)
        self.pay_no1_year_combo_box.SetSelection(5)
        self.pay_no1_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no1_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no1_mouth_combo_box.Enable(False)
        self.pay_no1_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no1_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no1_money_text_ctrl.Enable(False)
        self.pay_no1_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no1_checkbox.SetMinSize((25, 25))
        self.is_paid_no1_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no1_checkbox.Enable(False)
        self.pay_no2_checkbox.SetMinSize((90, 25))
        self.pay_no2_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no2_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no2_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no2_info_text_ctrl.Enable(False)
        self.pay_no2_year_combo_box.SetMinSize((60, 25))
        self.pay_no2_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no2_year_combo_box.Enable(False)
        self.pay_no2_year_combo_box.SetSelection(5)
        self.pay_no2_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no2_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no2_mouth_combo_box.Enable(False)
        self.pay_no2_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no2_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no2_money_text_ctrl.Enable(False)
        self.pay_no2_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no2_checkbox.SetMinSize((25, 25))
        self.is_paid_no2_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no2_checkbox.Enable(False)
        self.pay_no3_checkbox.SetMinSize((90, 25))
        self.pay_no3_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no3_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no3_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no3_info_text_ctrl.Enable(False)
        self.pay_no3_year_combo_box.SetMinSize((60, 25))
        self.pay_no3_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no3_year_combo_box.Enable(False)
        self.pay_no3_year_combo_box.SetSelection(5)
        self.pay_no3_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no3_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no3_mouth_combo_box.Enable(False)
        self.pay_no3_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no3_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no3_money_text_ctrl.Enable(False)
        self.pay_no3_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no3_checkbox.SetMinSize((25, 25))
        self.is_paid_no3_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no3_checkbox.Enable(False)
        self.pay_no4_checkbox.SetMinSize((90, 25))
        self.pay_no4_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no4_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no4_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no4_info_text_ctrl.Enable(False)
        self.pay_no4_year_combo_box.SetMinSize((60, 25))
        self.pay_no4_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no4_year_combo_box.Enable(False)
        self.pay_no4_year_combo_box.SetSelection(5)
        self.pay_no4_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no4_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no4_mouth_combo_box.Enable(False)
        self.pay_no4_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no4_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no4_money_text_ctrl.Enable(False)
        self.pay_no4_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no4_checkbox.SetMinSize((25, 25))
        self.is_paid_no4_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no4_checkbox.Enable(False)
        self.pay_no5_checkbox.SetMinSize((90, 25))
        self.pay_no5_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no5_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no5_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no5_info_text_ctrl.Enable(False)
        self.pay_no5_year_combo_box.SetMinSize((60, 25))
        self.pay_no5_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no5_year_combo_box.Enable(False)
        self.pay_no5_year_combo_box.SetSelection(5)
        self.pay_no5_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no5_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no5_mouth_combo_box.Enable(False)
        self.pay_no5_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no5_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no5_money_text_ctrl.Enable(False)
        self.pay_no5_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no5_checkbox.SetMinSize((25, 25))
        self.is_paid_no5_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no5_checkbox.Enable(False)
        self.pay_no6_checkbox.SetMinSize((90, 25))
        self.pay_no6_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no6_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no6_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no6_info_text_ctrl.Enable(False)
        self.pay_no6_year_combo_box.SetMinSize((60, 25))
        self.pay_no6_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no6_year_combo_box.Enable(False)
        self.pay_no6_year_combo_box.SetSelection(5)
        self.pay_no6_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no6_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no6_mouth_combo_box.Enable(False)
        self.pay_no6_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no6_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no6_money_text_ctrl.Enable(False)
        self.pay_no6_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no6_checkbox.SetMinSize((25, 25))
        self.is_paid_no6_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no6_checkbox.Enable(False)
        self.pay_no7_checkbox.SetMinSize((90, 25))
        self.pay_no7_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no7_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no7_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no7_info_text_ctrl.Enable(False)
        self.pay_no7_year_combo_box.SetMinSize((60, 25))
        self.pay_no7_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no7_year_combo_box.Enable(False)
        self.pay_no7_year_combo_box.SetSelection(5)
        self.pay_no7_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no7_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no7_mouth_combo_box.Enable(False)
        self.pay_no7_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no7_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no7_money_text_ctrl.Enable(False)
        self.pay_no7_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no7_checkbox.SetMinSize((25, 25))
        self.is_paid_no7_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no7_checkbox.Enable(False)
        self.pay_no8_checkbox.SetMinSize((90, 25))
        self.pay_no8_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no8_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no8_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no8_info_text_ctrl.Enable(False)
        self.pay_no8_year_combo_box.SetMinSize((60, 25))
        self.pay_no8_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no8_year_combo_box.Enable(False)
        self.pay_no8_year_combo_box.SetSelection(5)
        self.pay_no8_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no8_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no8_mouth_combo_box.Enable(False)
        self.pay_no8_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no8_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no8_money_text_ctrl.Enable(False)
        self.pay_no8_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no8_checkbox.SetMinSize((25, 25))
        self.is_paid_no8_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no8_checkbox.Enable(False)
        self.pay_no9_checkbox.SetMinSize((90, 25))
        self.pay_no9_checkbox.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no9_info_text_ctrl.SetMinSize((400, 35))
        self.pay_no9_info_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no9_info_text_ctrl.Enable(False)
        self.pay_no9_year_combo_box.SetMinSize((60, 25))
        self.pay_no9_year_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no9_year_combo_box.Enable(False)
        self.pay_no9_year_combo_box.SetSelection(5)
        self.pay_no9_mouth_combo_box.SetMinSize((45, 25))
        self.pay_no9_mouth_combo_box.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no9_mouth_combo_box.Enable(False)
        self.pay_no9_money_text_ctrl.SetMinSize((150, 30))
        self.pay_no9_money_text_ctrl.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.pay_no9_money_text_ctrl.Enable(False)
        self.pay_no9_money_text_ctrl.SetValidator(MyNumberValidator())
        self.is_paid_no9_checkbox.SetMinSize((25, 25))
        self.is_paid_no9_checkbox.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.is_paid_no9_checkbox.Enable(False)
        self.contract_paid_money_text_ctrl.SetMinSize((150, 35))
        self.contract_paid_money_text_ctrl.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_rest_money_text_ctrl.SetMinSize((150, 35))
        self.contract_rest_money_text_ctrl.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.contract_paid_proportion_text_ctrl.SetMinSize((100, 35))
        self.contract_paid_proportion_text_ctrl.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        self.save_contract_button.SetMinSize((1000, 50))
        self.save_contract_button.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"合同信息"), wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"付款明细"), wx.VERTICAL)
        sizer_24 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"合同列表"), wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(self.new_data_button, 0, wx.ALL, 3)
        sizer_5.Add(self.open_data_button, 0, wx.ALL, 3)
        sizer_5.Add(self.save_data_button, 0, wx.ALL, 3)
        sizer_5.Add(self.export_data_button, 0, wx.ALL, 3)
        sizer_5.Add(self.show_help_button, 0, wx.ALL, 3)
        sizer_5.Add(self.show_info_button, 0, wx.ALL, 3)
        sizer_1.Add(sizer_5, 0, wx.ALL | wx.EXPAND, 3)
        sizer_3.Add(self.add_contract_button, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_3.Add(self.remove_contract_button, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_3.Add(self.contract_moveup_button, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_3.Add(self.contract_movedown_button, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.contract_list_ctrl, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 5)
        sizer_7.Add((20, 20), 1, 0, 0)
        label_1 = wx.StaticText(self, wx.ID_ANY, u"数据标题", style=wx.ALIGN_CENTER | wx.ST_NO_AUTORESIZE)
        label_1.SetFont(
            wx.Font(17, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_7.Add(label_1, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_7.Add(self.work_title_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_7.Add((20, 20), 1, 0, 0)
        sizer_6.Add(sizer_7, 0, wx.BOTTOM | wx.EXPAND, 5)
        sizer_9.Add((20, 20), 1, 0, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, u"合同编号")
        label_2.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_9.Add(label_2, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_9.Add(self.contract_ID_text_ctrl, 0, 0, 0)
        sizer_9.Add((20, 20), 1, 0, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, u"合同名称")
        label_3.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_9.Add(label_3, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_9.Add(self.contract_title_text_ctrl, 0, 0, 0)
        sizer_9.Add((20, 20), 1, 0, 0)
        sizer_8.Add(sizer_9, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)
        sizer_10.Add((20, 20), 1, 0, 0)
        label_4 = wx.StaticText(self, wx.ID_ANY, u"供应商")
        label_4.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_10.Add(label_4, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_10.Add(self.contract_supplier_text_ctrl, 0, 0, 0)
        sizer_10.Add((20, 20), 1, 0, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, u"签订时间")
        label_5.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_10.Add(label_5, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_10.Add(self.contract_signed_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_18 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_18.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_10.Add(label_18, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_10.Add(self.contract_signed_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_19 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_19.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_10.Add(label_19, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_10.Add((20, 20), 1, 0, 0)
        label_6 = wx.StaticText(self, wx.ID_ANY, u"总金额（万元）")
        label_6.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_10.Add(label_6, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_10.Add(self.contract_total_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_10.Add((20, 20), 1, 0, 0)
        sizer_8.Add(sizer_10, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)
        sizer_16.Add((87, 30), 0, 0, 0)
        label_12 = wx.StaticText(self, wx.ID_ANY, u"序号")
        label_12.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_16.Add(label_12, 0, wx.ALIGN_CENTER, 0)
        sizer_16.Add((35, 20), 0, 0, 0)
        label_13 = wx.StaticText(self, wx.ID_ANY, u"启用")
        label_13.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_16.Add(label_13, 0, wx.ALIGN_CENTER, 0)
        sizer_16.Add((220, 20), 0, 0, 0)
        label_14 = wx.StaticText(self, wx.ID_ANY, u"付款说明")
        label_14.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_16.Add(label_14, 0, wx.ALIGN_CENTER, 0)
        sizer_16.Add((250, 20), 0, 0, 0)
        label_15 = wx.StaticText(self, wx.ID_ANY, u"付款时间")
        label_15.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_16.Add(label_15, 0, wx.ALIGN_CENTER, 0)
        sizer_16.Add((110, 20), 0, 0, 0)
        label_16 = wx.StaticText(self, wx.ID_ANY, u"付款金额（万元）")
        label_16.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_16.Add(label_16, 0, wx.ALIGN_CENTER, 0)
        sizer_16.Add((35, 20), 0, 0, 0)
        label_17 = wx.StaticText(self, wx.ID_ANY, u"已付款")
        label_17.SetFont(
            wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_16.Add(label_17, 0, wx.ALIGN_CENTER, 0)
        sizer_16.Add((38, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_15.Add((90, 40), 0, 0, 0)
        sizer_15.Add(self.pay_no1_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_15.Add((55, 20), 0, 0, 0)
        sizer_15.Add(self.pay_no1_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_15.Add((50, 20), 0, 0, 0)
        sizer_15.Add(self.pay_no1_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_10 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_10.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_15.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_15.Add(self.pay_no1_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_11 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_11.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_15.Add(label_11, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_15.Add((50, 20), 0, 0, 0)
        sizer_15.Add(self.pay_no1_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_15.Add((50, 20), 0, 0, 0)
        sizer_15.Add(self.is_paid_no1_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_15.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_15, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_17.Add((90, 40), 0, 0, 0)
        sizer_17.Add(self.pay_no2_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_17.Add((55, 20), 0, 0, 0)
        sizer_17.Add(self.pay_no2_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_17.Add((50, 20), 0, 0, 0)
        sizer_17.Add(self.pay_no2_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_20 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_20.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_17.Add(label_20, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_17.Add(self.pay_no2_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_21 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_21.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_17.Add(label_21, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_17.Add((50, 20), 0, 0, 0)
        sizer_17.Add(self.pay_no2_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_17.Add((50, 20), 0, 0, 0)
        sizer_17.Add(self.is_paid_no2_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_17.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_17, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_18.Add((90, 40), 0, 0, 0)
        sizer_18.Add(self.pay_no3_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_18.Add((55, 20), 0, 0, 0)
        sizer_18.Add(self.pay_no3_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_18.Add((50, 20), 0, 0, 0)
        sizer_18.Add(self.pay_no3_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_23 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_23.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_18.Add(label_23, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_18.Add(self.pay_no3_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_24 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_24.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_18.Add(label_24, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_18.Add((50, 20), 0, 0, 0)
        sizer_18.Add(self.pay_no3_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_18.Add((50, 20), 0, 0, 0)
        sizer_18.Add(self.is_paid_no3_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_18.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_18, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_19.Add((90, 40), 0, 0, 0)
        sizer_19.Add(self.pay_no4_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_19.Add((55, 20), 0, 0, 0)
        sizer_19.Add(self.pay_no4_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_19.Add((50, 20), 0, 0, 0)
        sizer_19.Add(self.pay_no4_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_26 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_26.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_19.Add(label_26, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_19.Add(self.pay_no4_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_27 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_27.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_19.Add(label_27, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_19.Add((50, 20), 0, 0, 0)
        sizer_19.Add(self.pay_no4_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_19.Add((50, 20), 0, 0, 0)
        sizer_19.Add(self.is_paid_no4_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_19.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_19, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_20.Add((90, 40), 0, 0, 0)
        sizer_20.Add(self.pay_no5_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_20.Add((55, 20), 0, 0, 0)
        sizer_20.Add(self.pay_no5_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_20.Add((50, 20), 0, 0, 0)
        sizer_20.Add(self.pay_no5_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_29 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_29.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_20.Add(label_29, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_20.Add(self.pay_no5_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_30 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_30.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_20.Add(label_30, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_20.Add((50, 20), 0, 0, 0)
        sizer_20.Add(self.pay_no5_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_20.Add((50, 20), 0, 0, 0)
        sizer_20.Add(self.is_paid_no5_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_20.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_20, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_21.Add((90, 40), 0, 0, 0)
        sizer_21.Add(self.pay_no6_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_21.Add((55, 20), 0, 0, 0)
        sizer_21.Add(self.pay_no6_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_21.Add((50, 20), 0, 0, 0)
        sizer_21.Add(self.pay_no6_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_32 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_32.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_21.Add(label_32, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_21.Add(self.pay_no6_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_33 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_33.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_21.Add(label_33, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_21.Add((50, 20), 0, 0, 0)
        sizer_21.Add(self.pay_no6_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_21.Add((50, 20), 0, 0, 0)
        sizer_21.Add(self.is_paid_no6_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_21.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_21, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_22.Add((90, 40), 0, 0, 0)
        sizer_22.Add(self.pay_no7_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_22.Add((55, 20), 0, 0, 0)
        sizer_22.Add(self.pay_no7_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_22.Add((50, 20), 0, 0, 0)
        sizer_22.Add(self.pay_no7_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_35 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_35.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_22.Add(label_35, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_22.Add(self.pay_no7_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_36 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_36.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_22.Add(label_36, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_22.Add((50, 20), 0, 0, 0)
        sizer_22.Add(self.pay_no7_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_22.Add((50, 20), 0, 0, 0)
        sizer_22.Add(self.is_paid_no7_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_22.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_22, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_23.Add((90, 40), 0, 0, 0)
        sizer_23.Add(self.pay_no8_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_23.Add((55, 20), 0, 0, 0)
        sizer_23.Add(self.pay_no8_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_23.Add((50, 20), 0, 0, 0)
        sizer_23.Add(self.pay_no8_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_38 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_38.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_23.Add(label_38, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_23.Add(self.pay_no8_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_39 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_39.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_23.Add(label_39, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_23.Add((50, 20), 0, 0, 0)
        sizer_23.Add(self.pay_no8_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_23.Add((50, 20), 0, 0, 0)
        sizer_23.Add(self.is_paid_no8_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_23.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_23, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_24.Add((90, 40), 0, 0, 0)
        sizer_24.Add(self.pay_no9_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_24.Add((55, 20), 0, 0, 0)
        sizer_24.Add(self.pay_no9_info_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_24.Add((50, 20), 0, 0, 0)
        sizer_24.Add(self.pay_no9_year_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_41 = wx.StaticText(self, wx.ID_ANY, u"年")
        label_41.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_24.Add(label_41, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_24.Add(self.pay_no9_mouth_combo_box, 0, wx.ALIGN_CENTER, 0)
        label_42 = wx.StaticText(self, wx.ID_ANY, u"月")
        label_42.SetFont(
            wx.Font(13, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_24.Add(label_42, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_24.Add((50, 20), 0, 0, 0)
        sizer_24.Add(self.pay_no9_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_24.Add((50, 20), 0, 0, 0)
        sizer_24.Add(self.is_paid_no9_checkbox, 0, wx.ALIGN_CENTER, 0)
        sizer_24.Add((42, 20), 0, wx.EXPAND, 0)
        sizer_14.Add(sizer_24, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_14, 0, wx.ALL | wx.EXPAND, 10)
        sizer_13.Add((20, 20), 1, 0, 0)
        label_7 = wx.StaticText(self, wx.ID_ANY, u"已付金额（万元）")
        label_7.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_13.Add(label_7, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_13.Add(self.contract_paid_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_13.Add((20, 20), 1, 0, 0)
        label_8 = wx.StaticText(self, wx.ID_ANY, u"剩余金额（万元）")
        label_8.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_13.Add(label_8, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_13.Add(self.contract_rest_money_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_13.Add((20, 20), 1, 0, 0)
        label_9 = wx.StaticText(self, wx.ID_ANY, u"已付款比例")
        label_9.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Microsoft YaHei UI"))
        sizer_13.Add(label_9, 0, wx.ALIGN_CENTER | wx.RIGHT, 10)
        sizer_13.Add(self.contract_paid_proportion_text_ctrl, 0, wx.ALIGN_CENTER, 0)
        sizer_13.Add((20, 20), 1, 0, 0)
        sizer_8.Add(sizer_13, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)
        sizer_8.Add(self.save_contract_button, 0, wx.ALIGN_CENTER | wx.ALL, 20)
        sizer_6.Add(sizer_8, 1, wx.ALL | wx.EXPAND, 5)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def new_data(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'new_data' not implemented!")
        event.Skip()

    def open_data(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'open_data' not implemented!")
        event.Skip()

    def save_data(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'save_data' not implemented!")
        event.Skip()

    def export_data(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'export_data' not implemented!")
        event.Skip()

    def show_help(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'show_help' not implemented!")
        event.Skip()

    def show_info(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'show_info' not implemented!")
        event.Skip()

    def add_contract(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'add_contract' not implemented!")
        event.Skip()

    def remove_contract(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'remove_contract' not implemented!")
        event.Skip()

    def contract_moveup(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'contract_moveup' not implemented!")
        event.Skip()

    def contract_movedown(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'contract_movedown' not implemented!")
        event.Skip()

    def load_contract(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'load_contract' not implemented!")
        event.Skip()

    def work_title_change(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'work_title_change' not implemented!")
        event.Skip()

    def pay_money_changed(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'pay_money_changed' not implemented!")
        event.Skip()

    def pay_enable(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'pay_enable' not implemented!")
        event.Skip()

    def save_contract(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'save_contract' not implemented!")
        event.Skip()


# end of class MyFrame

class ExportFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ExportFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE | wx.FRAME_FLOAT_ON_PARENT
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1366, 768))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ExportFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ExportFrame.__do_layout
        sizer_26 = wx.BoxSizer(wx.VERTICAL)
        sizer_26.Add((0, 0), 0, 0, 0)
        self.SetSizer(sizer_26)
        self.Layout()
        self.Centre()
        # end wxGlade


# end of class ExportFrame

class MyApp(wx.App):
    def OnInit(self):
        self.main_frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.main_frame)
        self.main_frame.Show()
        return True


# end of class MyApp

if __name__ == "__main__":
    Contract_Statistics = MyApp(0)
    Contract_Statistics.MainLoop()
